import 'styles/globals.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ background: 'black' }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
